// <auto-generated />
namespace BlogCentralVersion2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class lagttileierfeltidb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lagttileierfeltidb));
        
        string IMigrationMetadata.Id
        {
            get { return "201410071901069_lagt til eierfelt i db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
